spring:
  application:
    name: bbqms
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DB_URL}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
  flyway:
    schemas: ${DB_SCHEMA}

jwt:
  header-title: Authorization
  token-prefix: Bearer
  secret-key: ${JWT_KEY}
  authorities-key: USER_AUTHORITIES
  token-validity-time: PT30M
tfa:
  label: BBQMS
  issuer: BBQMS
tenancy:
  default-code: DFLT
notifications:
  expo-url: https://exp.host/--/api/v2/push/send
  mock: true
