spring:
  application:
    name: bbqms
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    schemas: ${DB_SCHEMA}
